### ISSUE TITLE
Add mentions of linters.

### ISSUE THREAD

**Issue by jamesturk** [uchicago-cs/student-resource-guide#18]
In recent years, many if not most open source projects & organizations have adopted tools like `flake8`, `pylint`, `black`, and `isort` to detect & prevent style issues.  (`black` is officially a Python Software Foundation project now, driving a lot more adoption as of late.)

- https://github.com/psf/black
- https://github.com/PyCQA

If there's interest, I'd be glad to write a section on these tools.

**Comment by borjasotomayor** [comment]
I think this could be a valuable addition; were you thinking it would go in the style guide?

**Comment by jamesturk** [comment]
Yes I think that'd make sense, I'll write up a draft when I get a chance.
